services:
  segmentation:
    image: ${SEGMENTATION_IMAGE}
    user: "${UID}:${GID}"
    container_name: segmentation_service
    shm_size: 2g
    volumes:
      - ${MOUNTDIR}:${MOUNTDIR}
    ports:
      - "8001:8001"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all            # pass ALL GPUs
              capabilities: [gpu]   # or [gpu, utility]
    environment:
      WORKDIR: ${WORKDIR}
    restart: no
    networks:
      - my_network

  converter:
    image: ${CONVERTER_IMAGE}
    user: "${UID}:${GID}"
      # build: converter/
    container_name: fastapi_service
    ports:
      - "8000:8000"
    volumes:
      #       - "${WORKDIR}:/home/.potree"
      # - ${WORKDIR}:/workdir
      - ${MOUNTDIR}:${MOUNTDIR}
    environment:
      WORKDIR: ${WORKDIR}
    restart: unless-stopped
    networks:
      - my_network

networks:
  my_network:
    driver: bridge

